### ISSUE TITLE
how to get the password

### ISSUE THREAD

**Issue by nguyenhuutinh** [linuxdream/sailsjs-base#1]
Hi, how to get the password from the link?

link: `${sails.config.urls.fe_url}/#/validate?e=${encodeURI( user.email )}&p=${encodeURI( randomPass )}`

**Comment by linuxdream** [comment]
I'm not entirely sure what you are asking. That section of the AuthController sends the user a one-time use link to enter the site. There is no traditional password creation/login per se. If you did NOT want to use a magic link, you would need to make the necessary changes to the AuthController.signup and AuthController.signin endpoints to accept a password and to set and check them accordingly.

**Comment by nguyenhuutinh** [comment]
thanks a lot
